Supporting full-fledged URLs for authelia URL (instead of domain:port)
HeavenVolkoff/caddy-authelia pull request #1
Opened 2021-01-19 17:37 UTC by clems71

- Fixes the case where authelia is hosted on a path, not a subdomain (like cloud.example.com/auth)
- Simplifies the handler: no need for TLS flag, neither port : relying on URL now.
- Improved doc

2021-01-20 19:13 UTC, HeavenVolkoff commented
Hey, thanks for your interest in this project and for the PR.
I gave your changes a quick look yesterday, and they look good to me.
Today or tomorrow I will test them out, and if everything is working fine, I will merge this

2021-01-22 22:25 UTC, clems71 commented
Hey! Did you had a chance to test the PR? I'm about to rebuild a caddy binary with your plugin, so just wondering!

2021-01-23 01:48 UTC, HeavenVolkoff commented
> Hey! Did you had a chance to test the PR? I'm about to rebuild a caddy binary with your plugin, so just wondering!

Hey, sorry I wasn't able to test it yet, had some family issues. But start of next week I will have some time to test it properly.

By the way I left a comment about the `X-Forwarded-Host` header rule in your README, did you read it?

2021-01-23 22:54 UTC, clems71 commented
Hey, no problem. No didn't read the comment. I double checked, and couldn't find it on Github. Maybe still in draft on your end ?
Regards

2021-01-24 00:11 UTC, HeavenVolkoff requested changes

2021-01-24 00:11 UTC, HeavenVolkoff commented on README.md
> +    request_header X-Forwarded-Host {http.request.host}
This shouldn't be necessary. The code below should already be assigning all the headers needed by the authelia `/api/verify` request:
https://github.com/HeavenVolkoff/caddy-authelia/blob/ca9e35288d873885443b3dc3669d4d3de0dc0ea3/plugin/internalized/traefik/write_headers.go#L50-L58

Is this not working for you?

2021-02-19 18:18 UTC, HeavenVolkoff commented on README.md
> +    request_header X-Forwarded-Host {http.request.host}
Ok, now I understand the problem here. The AssignForwardHeaders function is only executed during the api calls made to authelia. But these headers seems to also be required when you open the authelia frontend to sign-in with 2FA, and accessing that goes through another set of caddy directives which this plugin does not handle. I will look for a way to solve this automatically with the plugin, but for now this seems to be the best solution.

2021-02-19 18:24 UTC, HeavenVolkoff commented
LGTM

I have done some minimal tests, and everything seems fine.

In the future I will try to write some github action to test this plugin automatically.

Anyway, thanks for you contribution.

2021-02-19 18:24 UTC, HeavenVolkoff approved these changes

2021-02-19 18:24 UTC, merged